export const LANDING = "/"
export const CONTACT = "/contact"
export const COWORK = "/cowork"
export const DONATE = "/donate"
export const SPONSORS = "/sponsors"
export const EVENTS = "/events"

export const SIGNIN = "/app/sign-in"
export const SIGNUP = "/app/sign-up"
export const RESETPASSWORD = "/app/reset-password"
export const APPHOME = "/app"
export const ACCOUNT = "/app/account"
export const PURCHASE = "/app/purchase"
export const ORDER = "/app/order"

export const INSTAGRAM = "https://instagram.com/progressbar_sk"
export const FACEBOOK = "https://facebook.com/progressbar"
export const AUTHORS = "https://github.com/Progressbar/web2/graphs/contributors"
export const CULTURECOC = "https://github.com/Progressbar/culture"
export const PRESSKIT = "https://github.com/Progressbar/presskit"
export const PIP = "https://github.com/Progressbar/Progressbar-Improvement-Proposal"
export const SPACEMAP = "https://github.com/Progressbar/space-map"
